---
output: 
  phstemplates::phs_report_docx:
    reference_docx: "/conf/LIST_analytics/West Hub/02 - Scaled Up Work/RMarkdown/Locality Profiles/Master RMarkdown Document & Render Code/phs-mngtinfo-report.docx"
    fig_caption: no
    cover_page: "/conf/LIST_analytics/West Hub/02 - Scaled Up Work/RMarkdown/Locality Profiles/Master RMarkdown Document & Render Code/phs-mngtinfo-cover.docx"
    cover_title: "My Title"
    cover_subtitle: "My subtitle"
    cover_date: "DD MM YYYY"
    toc_depth: 3
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(kableExtra.auto_format = FALSE)

# Line below for testing only
Loc <- "Teviot and Liddesdale"

locality <- Loc
LOCALITY <- Loc
lp_path <- "/conf/LIST_analytics/West Hub/02 - Scaled Up Work/RMarkdown/Locality Profiles/"

# stop(getwd())

source("Master RMarkdown Document & Render Code/Global Script.R")
source("Services/2. Services data manipulation & table.R")
source("Services/3. Service HSCP map.R")

x <- 1 # object for figure numbers
y <- 1 # object for table numbers
```


# Services


<Div custom-style = "Table or chart caption">Figure `r x`: Map of services by locality in `r HSCP` HSCP^2^.</Div>
\newline

```{r echo = FALSE, fig.width=6, fig.cap= "A map of the health and social care partnership including a breakdown on localities with the locations of all the GP practices, care homes, emergency depertments and minor injury units."}
service_map

x <- x + 1
```

\newline

<Div custom-style = "Table or chart caption">Table `r y`: Number of each type of service in `r LOCALITY` Locality^2^.</Div>
\newline

```{r echo = FALSE}

flextable(services_tibble, theme_fun = NULL) %>%
  my_ft_format() %>%
  set_header_labels(values = c(
"Service Type", "Service", "Number"
  )) %>%
  bold(j = 1) %>%
  width(width=4/ncol(services_tibble))

y <- y + 1
```
