```{r load_packages, include=FALSE}
library(knitr)
library(flextable)
library(officer)
library(officedown)
```

{{contents_anchor}}

# Summary Table

```{r locality_names, include=FALSE}
# Set locality name object (with automatic wrapping)
loc_name <- paste(LOCALITY, "Locality", sep = "\n") |>
  str_wrap(width = case_when(n_loc < 4 ~ 20, n_loc == 4 ~ 15, n_loc > 4 ~ 8))

# Set other localities names
other_loc_names <- paste(other_locs$hscp_locality, "Locality", sep = "\n") |>
  str_wrap(width = case_when(n_loc < 4 ~ 20, n_loc == 4 ~ 15, n_loc > 4 ~ 8))

# Set HSCP name object
hscp_name <- paste(HSCP, "HSCP") |>
  str_wrap(width = if_else(n_loc < 3, 25, 10))

# Set the headings (We will add the first heading per table)
headings <- c(
  "Data Type",
  "Time Period",
  loc_name,
  other_loc_names,
  hscp_name,
  "Scotland"
)
```

```{r summary_table_func, include=FALSE}
make_summary_table <- function(data) {
  info_cols <- 1:4
  loc_col <- 5
  other_loc_cols <- 6:(ncol(data) - 2)
  hscp_col <- ncol(data) - 1
  scot_col <- ncol(data)

  # Identify section boundaries
  section_starts <- which(!duplicated(data$Section))
  section_ends <- c(section_starts[-1] - 1, nrow(data))


  ft <- data |>
    flextable() |>
    # Merge Section column
    merge_v(j = "Section") |>
    valign(j = "Section", valign = "top") |>
    # Header styling
    font(part = "header", fontname = "Arial") |>
    fontsize(part = "header", size = 10) |>
    bold(part = "header") |>
    color(part = "header", color = "white") |>
    bg(part = "header", bg = phs_colours("phs-purple")) |>
    # Body styling
    bold(j = 1:2, part = "body") |>
    font(part = "body", fontname = "Arial") |>
    fontsize(part = "body", size = 10) |>
    bg(j = info_cols, part = "body", bg = phs_colours("phs-graphite-30")) |>
    bg(j = loc_col, part = "body", bg = phs_colours("phs-purple-30")) |>
    bg(j = other_loc_cols, part = "body", bg = phs_colours("phs-magenta-30")) |>
    bg(j = hscp_col, part = "body", bg = phs_colours("phs-blue-30")) |>
    bg(j = scot_col, part = "body", bg = phs_colours("phs-green-30")) |>
    # Base borders
    border(border = fp_border(color = "white", width = 1), part = "body")

  # Add soft grey divider (except first section)
  ft <- hline(
    ft,
    i = section_ends,
    border = fp_border(color = "#BFBFBF", width = 2),
    part = "body"
  )

  ft |> set_table_properties(layout = "autofit")
}
```

```{r demographics}
indicators <- c(
  "Total population",
  "Ratio male to female",
  "Population over 65",
  "Population in the least deprived SIMD quintile",
  "Population in the most deprived SIMD quintile"
)
# List what data type they are
datatype <- c("count", "ratio", "%", "%", "%")
# Enter the time periods available
time <- c(pop_max_year, pop_max_year, pop_max_year, "2020", "2020")

loc_values <- c(total_population, paste0("1:", gender_ratio), over65, perc_top_quintile, perc_bottom_quintile)

other_loc_values <- rbind(other_locs_total_pop, other_locs_gender_ratio, other_locs_over65, other_locs_simd)
hscp_values <- c(hscp_total_pop, hscp_gender_ratio, hscp_over65, hscp_simd_top, hscp_simd_bottom)
scot_values <- c(scot_total_pop, scot_gender_ratio, scot_over65, 20, 20)

demographic_values <- tibble(
  Section = "Demographics",
  Indicator = indicators,
  Datatype = datatype,
  Time = time,
  loc_values,
  other_loc_values,
  hscp_values,
  scot_values
)

colnames(demographic_values) <- c("Section", "Indicator", "Data Type", "Time Period", headings[-c(1, 2)])
```

```{r housing}
indicators <- c(
  "Total number of households",
  "Households with single occupant tax discount",
  "Households in Council Tax Band A-C",
  "Households in Council Tax Band F-H"
)

datatype <- c("count", "%", "%", "%")

time <- as.character(c(max_year_housing, max_year_housing, max_year_housing, max_year_housing))

# Values
loc_values <- c(n_houses, perc_single_discount, perc_houses_AC, perc_houses_FH)
other_loc_values <- rbind(other_locs_n_houses, other_locs_perc_discount, other_locs_perc_housesAC, other_locs_perc_housesFH)
hscp_values <- c(hscp_n_houses, hscp_perc_discount, hscp_perc_housesAC, hscp_perc_housesFH)
scot_values <- c(scot_n_houses, scot_perc_discount, scot_perc_housesAC, scot_perc_housesFH)

housing_values <- tibble(
  Section = "Housing",
  Indicator = indicators,
  Datatype = datatype,
  Time = time,
  loc_values,
  other_loc_values,
  hscp_values,
  scot_values
)

colnames(housing_values) <- c("Section", "Indicator", "Data Type", "Time Period", headings[-c(1, 2)])
```

```{r population_health}
indicators <- c(
  "Male average life expectancy in years",
  "Female average life expectancy in years",
  "Deaths aged 15-44 per 100,000",
  "Population estimated to have at least one LTC",
  "Cancer registrations per 100,000",
  "Anxiety, depression & psychosis prescriptions"
)

datatype <- c("mean", "mean", "rate", "%", "rate", "%")

time <- c(
  paste0(latest_period_life_exp_loc, "*"),
  paste0(latest_period_life_exp_loc, "*"),
  latest_period_deaths_15_44,
  latest_year_ltc,
  latest_period_cancer_reg,
  latest_period_adp_presc
)

# Values

loc_values <- round_half_up(c(avg_life_exp_latest_male, avg_life_exp_latest_fem, deaths_15_44_latest, ltc_percent_total_latest, cancer_reg_rate_latest, adp_presc_latest), 1)
other_loc_values <- rbind(other_locs_life_exp_male, other_locs_life_exp_fem, other_locs_deaths_15_44, other_locs_ltc, other_locs_cancer, other_locs_adp)
hscp_values <- c(hscp_life_exp_male, hscp_life_exp_fem, hscp_deaths_15_44, hscp_ltc, hscp_cancer, hscp_adp)
scot_values <- c(scot_life_exp_male, scot_life_exp_fem, scot_deaths_15_44, ltc_perc_scot, scot_cancer, scot_adp_presc)

population_health_values <- tibble(
  Section = "Population Health",
  Indicator = indicators,
  Datatype = datatype,
  Time = time,
  loc_values,
  other_loc_values,
  hscp_values,
  scot_values
) |> mutate(across(everything(), as.character))

colnames(population_health_values) <- c("Section", "Indicator", "Data Type", "Time Period", headings[-c(1, 2)])
```

```{r lifestyle_risk_factors}
indicators <- c(
  "Alcohol-related hospital admissions per 100,000",
  "Alcohol-specific mortality per 100,000",
  "Drug-related hospital admissions per 100,000",
  "Bowel screening uptake"
)

datatype <- c("rate", "rate", "rate", "%")

time <- c(
  latest_period_alcohol_hosp,
  latest_period_alcohol_deaths,
  str_wrap(latest_period_drug_hosp, 9),
  latest_period_bowel_screening
)

# Values
loc_values <- round_half_up(c(alcohol_hosp_latest, alcohol_deaths_latest, drug_hosp_latest, bowel_screening_latest), 1)
other_loc_values <- rbind(other_locs_alcohol_hosp, other_locs_alcohol_deaths, other_locs_drug_hosp, other_locs_bowel_screening)
hscp_values <- c(hscp_alcohol_hosp, hscp_alcohol_deaths, hscp_drug_hosp, hscp_bowel_screening)
scot_values <- c(scot_alcohol_hosp, scot_alcohol_deaths, scot_drug_hosp, scot_bowel_screening)

lifestyle_values <- tibble(
  Section = "Lifestyle and Risk Factors",
  Indicator = indicators,
  Datatype = datatype,
  Time = time,
  loc_values,
  other_loc_values,
  hscp_values,
  scot_values
) |> mutate(across(everything(), as.character))

colnames(lifestyle_values) <- c("Section", "Indicator", "Data Type", "Time Period", headings[-c(1, 2)])
```

```{r hospital_community_care}
indicators <- c(
  "Emergency admissions per 100,000",
  "Unscheduled bed days per 100,000",
  "A&E attendances per 100,000",
  "Delayed discharges (65+) per 100,000",
  "Potentially Preventable Admissions per 100,000"
)
datatype <- c("rate", "rate", "rate", "rate", "rate")
time <- c(max_fy, max_fy, max_fy, max_fy, max_fy)

# Values
loc_values <- format(
  c(latest_emergency_adm_loc1, latest_bed_days_loc1, latest_ae_att_loc1, latest_dd_loc1, latest_ppa_loc1),
  big.mark = ","
)
other_loc_values <- bind_rows(other_loc_emergency_adm, other_loc_bed_days, other_loc_ae_att, other_loc_dd, other_loc_ppa)
hscp_values <- format(
  c(hscp_emergency_adm$data, hscp_bed_days$data, hscp_ae_att$data, hscp_dd$data, filter(hscp_ppa, year == max(year))$data),
  big.mark = ","
)
scot_values <- format(
  c(scot_emergency_adm$data, scot_bed_days$data, scot_ae_att$data, scot_dd$data, filter(scot_ppa, year == max(year))$data),
  big.mark = ","
)

usc_values <- tibble(
  Section = "Hospital & Community Care",
  Indicator = indicators,
  Datatype = datatype,
  Time = time,
  loc_values,
  other_loc_values,
  hscp_values,
  scot_values
)

colnames(usc_values) <- c("Section", "Indicator", "Data Type", "Time Period", headings[-c(1, 2)])
```

```{r hospital_mental_health}
indicators <- c(
  "Psychiatric patient hospitalisations per 100,000",
  "Unscheduled bed days per 100,000"
)
datatype <- c("rate", "rate")
time <- c(str_wrap(latest_period_psych_hosp, 9), max_fy)

# Values
loc_values <- c(
  format(psych_hosp_latest, big.mark = ","),
  format(
    ifelse(is_empty(latest_bed_days_mh_loc1), NA_real_, latest_bed_days_mh_loc1),
    big.mark = ","
  )
)

other_loc_values <- bind_rows(other_locs_psych_hosp, other_loc_bed_days_mh)
hscp_values <- c(
  format(filter(hscp_psych_hosp, year == max(year))$measure, big.mark = ","),
  format(hscp_bed_days_mh$data, big.mark = ",")
)
scot_values <- c(
  format(filter(scot_psych_hosp, year == max(year))$measure, big.mark = ","),
  format(scot_bed_days_mh$data, big.mark = ",")
)


usc_mh_values <- tibble(
  indicators, datatype, time, loc_values, other_loc_values,
  hscp_values, scot_values
)

colnames(usc_mh_values) <- c("Hospital Care (Mental Health) Indicators", headings)


usc_mh_values <- tibble(
  Section = "Hospital (Mental Health) Care",
  Indicator = indicators,
  Datatype = datatype,
  Time = time,
  loc_values,
  other_loc_values,
  hscp_values,
  scot_values
)

colnames(usc_mh_values) <- c("Section", "Indicator", "Data Type", "Time Period", headings[-c(1, 2)])
```

```{r table}
summary_all1 <- bind_rows(
  demographic_values,
  housing_values,
  population_health_values
)

summary_all1 <- summary_all1 |>
  group_by(Section) |>
  ungroup()

summary_table1 <- make_summary_table(summary_all1)

summary_table1

ftext(
  glue("*at HSCP and Scotland level, the time period is a 3-year aggregate ({latest_period_life_exp_otherareas})"), superscript_style
)
```

\newline

```{r table2}
summary_all2 <- bind_rows(
  lifestyle_values,
  usc_values,
  usc_mh_values
)

summary_all2 <- summary_all2 |>
  group_by(Section) |>
  ungroup()

summary_table2 <- make_summary_table(summary_all2)

summary_table2
```



{{summary_anchor}}
