---
title: ''
output: 
  word_document:
    reference_docx: "/conf/LIST_analytics/West Hub/02 - Scaled Up Work/RMarkdown/Locality Profiles/Summary Table/ST_ref_doc.docx"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = NA)
# Lines below for testing only:
# LOCALITY <- "Falkirk West"
# LOCALITY <- "Stirling City with the Eastern Villages Bridge of Allan and Dunblane"
# LOCALITY <- "Mid-Argyll, Kintyre and Islay"
# LOCALITY <- "City of Dunfermline"
# LOCALITY <- "Barra"
# LOCALITY <- "Whalsay and Skerries"
# LOCALITY <- "Inverclyde East"

## Project file path
lp_path <- "/conf/LIST_analytics/West Hub/02 - Scaled Up Work/RMarkdown/Locality Profiles/"

# Source in global functions/themes script
# source("Master RMarkdown Document & Render Code/Global Script.R")

# # demographics
# source("Demographics/1. Demographics - Population.R")
# source("Demographics/2. Demographics - SIMD.R")
#
# # housing
# source("Households/Households Code.R")
#
# # general health
# source("General Health/3. General Health Outputs.R")
#
# # lifestyle & risk factors
# source("Lifestyle & Risk Factors/2. Lifestyle & Risk Factors Outputs.R")
#
# # unscheduled care
# source("Unscheduled Care/2. Unscheduled Care outputs.R")

library(knitr)
library(flextable)
library(officer)
library(officedown)
```

```{r locality_names}
# Set locality name object (with automatic wrapping)

loc_name <- paste(LOCALITY, "Locality", sep = "\n") |>
  str_wrap(width = case_when(n_loc < 4 ~ 20, n_loc == 4 ~ 15, n_loc > 4 ~ 8))

# Set other localities df

otherloc_names <- paste(other_locs$hscp_locality, "Locality", sep = "\n") |>
  str_wrap(width = case_when(n_loc < 4 ~ 20, n_loc == 4 ~ 15, n_loc > 4 ~ 8))
otherloc_names <- tibble(loc_number = 2:n_loc, otherloc_names) |>
  pivot_wider(names_from = loc_number, values_from = otherloc_names)

# Set HSCP name object
hscp_name <- paste0(HSCP, "\nHSCP") |>
  strwrap(width = if_else(n_loc < 3, 30, 12))


summary_table <- tibble(
  Indicators = "Indicators",
  Data_Type = "Data Type",
  Time_Period = "Time Period",
  Locality = loc_name,
  Other_Localities = otherloc_names,
  HSCP = hscp_name,
  Scotland = "Scotland"
)
```

## Demographics Summary Table

```{r demographics}
indicators <- c(
  "Total population",
  "Gender ratio male to female",
  "Population over 65",
  "Population in least deprived SIMD quintile",
  "Population in most deprived SIMD quintile"
) |> str_wrap(width = 30)
# List what data type they are
datatype <- c("count", "ratio", "%", "%", "%")
# Enter the time periods available
time <- c(pop_max_year, pop_max_year, pop_max_year, "2020", "2020")

loc_values <- c(total_population, paste0("1:", gender_ratio), over65, perc_top_quintile, perc_bottom_quintile)

other_loc_values <- rbind(other_locs_total_pop, other_locs_gender_ratio, other_locs_over65, other_locs_simd)
hscp_values <- c(hscp_total_pop, hscp_gender_ratio, hscp_over65, hscp_simd_top, hscp_simd_bottom)
scot_values <- c(scot_total_pop, scot_gender_ratio, scot_over65, 20, 20)

demographic_values <- tibble(
  indicators, datatype, time, loc_values, other_loc_values,
  hscp_values, scot_values
)

headings <- as.character(unlist(summary_table[1, ]))

colnames(demographic_values) <- headings

demographics <- flextable(demographic_values) |>
  bold(part = "header") |>
  bold(j = 1, bold = TRUE, part = "body") |>
  fontsize(part = "header", size = 12) |>
  font(part = "body", fontname = "Arial") |>
  font(part = "header", fontname = "Arial") |>
  color(part = "header", color = "white") |>
  bg(part = "header", bg = "#3F3685") |>
  bg(j = 1:3, part = "body", bg = "grey90") |>
  border(border = fp_border(color = "white", width = 1), part = "body") |>
  set_table_properties(layout = "autofit")

demographics
```

## Housing Summary Table

```{r housing}
indicators <- c(
  "Total number of households",
  "Households with single occupant tax discount",
  "Households in Council Tax Band A-C",
  "Households in Council Tax Band F-H"
) |> str_wrap(width = 30)

datatype <- c("count", "%", "%", "%")

time <- c(max_year_housing, max_year_housing, max_year_housing, max_year_housing)

# Values
loc_values <- c(n_houses, perc_single_discount, perc_houses_AC, perc_houses_FH)
other_loc_values <- rbind(other_locs_n_houses, other_locs_perc_discount, other_locs_perc_housesAC, other_locs_perc_housesFH)
hscp_values <- c(hscp_n_houses, hscp_perc_discount, hscp_perc_housesAC, hscp_perc_housesFH)
scot_values <- c(scot_n_houses, scot_perc_discount, scot_perc_housesAC, scot_perc_housesFH)


housing_values <- tibble(
  indicators, datatype, time, loc_values, other_loc_values,
  hscp_values, scot_values
)


headings <- as.character(unlist(summary_table[1, ]))

colnames(housing_values) <- headings

housing_table <- flextable(housing_values) |>
  bold(part = "header") |>
  bold(j = 1, bold = TRUE, part = "body") |>
  fontsize(part = "header", size = 12) |>
  font(part = "body", fontname = "Arial") |>
  font(part = "header", fontname = "Arial") |>
  color(part = "header", color = "white") |>
  bg(part = "header", bg = "#3F3685") |>
  bg(j = 1:3, part = "body", bg = "grey90") |>
  border(border = fp_border(color = "white", width = 1), part = "body") |>
  set_table_properties(layout = "autofit")

housing_table <- colformat_num(housing_table,
  j = "Time Period", # The column name
  big.mark = "", # Remove thousand separator
  digits = 0
)

housing_table
```

## General Health Summary Table

```{r general_health}
indicators <- c(
  "Male average life expectancy in years",
  "Female average life expectancy in years",
  "Deaths aged 15-44 per 100,000",
  "Population with long-term condition",
  "Cancer registrations per 100,000",
  "Anxiety, depression & psychosis prescriptions"
) |> str_wrap(width = 30)

datatype <- c("mean", "mean", "rate", "%", "rate", "%")

time <- c(
  paste0(latest_period_life_exp_loc, "*"),
  paste0(latest_period_life_exp_loc, "*"),
  latest_period_deaths_15_44,
  latest_year_ltc,
  latest_period_cancer_reg,
  latest_period_adp_presc
)

# Values

loc_values <- round_half_up(c(avg_life_exp_latest_male, avg_life_exp_latest_fem, deaths_15_44_latest, ltc_percent_total_latest, cancer_reg_rate_latest, adp_presc_latest), 1)
other_loc_values <- rbind(other_locs_life_exp_male, other_locs_life_exp_fem, other_locs_deaths_15_44, other_locs_ltc, other_locs_cancer, other_locs_adp)
hscp_values <- c(hscp_life_exp_male, hscp_life_exp_fem, hscp_deaths_15_44, hscp_ltc, hscp_cancer, hscp_adp)
scot_values <- c(scot_life_exp_male, scot_life_exp_fem, scot_deaths_15_44, scot_ltc, scot_cancer, scot_adp_presc)


general_health_values <- tibble(
  indicators, datatype, time, loc_values, other_loc_values,
  hscp_values, scot_values
)


colnames(general_health_values) <- headings

general_health_table <- flextable(general_health_values) |>
  bold(part = "header") |>
  bold(j = 1, bold = TRUE, part = "body") |>
  fontsize(part = "header", size = 12) |>
  font(part = "body", fontname = "Arial") |>
  font(part = "header", fontname = "Arial") |>
  color(part = "header", color = "white") |>
  bg(part = "header", bg = "#3F3685") |>
  bg(j = 1:3, part = "body", bg = "grey90") |>
  border(border = fp_border(color = "white", width = 1), part = "body") |>
  set_table_properties(layout = "autofit")

general_health_table
```

###### \*At HSCP and Scotland level, the time period is a 3-year aggregate (`r latest_period_life_exp_otherareas`)

## Lifestyle & Risk Factors Summary Table

```{r lifestyle_risk_factors}
indicators <- c(
  "Alcohol-related hospital admissions per 100,000",
  "Alcohol-specific mortality per 100,000",
  "Drug-related hospital admissions per 100,000",
  "Bowel screening uptake"
) |> str_wrap(width = 30)

datatype <- c("rate", "rate", "rate", "%")

time <- c(
  latest_period_alcohol_hosp,
  latest_period_alcohol_deaths,
  str_wrap(latest_period_drug_hosp, 9),
  latest_period_bowel_screening
)

# Values
loc_values <- round_half_up(c(alcohol_hosp_latest, alcohol_deaths_latest, drug_hosp_latest, bowel_screening_latest), 1)
other_loc_values <- rbind(other_locs_alcohol_hosp, other_locs_alcohol_deaths, other_locs_drug_hosp, other_locs_bowel_screening)
hscp_values <- c(hscp_alcohol_hosp, hscp_alcohol_deaths, hscp_drug_hosp, hscp_bowel_screening)
scot_values <- c(scot_alcohol_hosp, scot_alcohol_deaths, scot_drug_hosp, scot_bowel_screening)


lifestyle_values <- tibble(
  indicators, datatype, time, loc_values, other_loc_values,
  hscp_values, scot_values
)


colnames(lifestyle_values) <- headings

lifestyle_table <- flextable(lifestyle_values) |>
  bold(part = "header") |>
  bold(j = 1, bold = TRUE, part = "body") |>
  fontsize(part = "header", size = 12) |>
  font(part = "body", fontname = "Arial") |>
  font(part = "header", fontname = "Arial") |>
  color(part = "header", color = "white") |>
  bg(part = "header", bg = "#3F3685") |>
  bg(j = 1:3, part = "body", bg = "grey90") |>
  border(border = fp_border(color = "white", width = 1), part = "body") |>
  set_table_properties(layout = "autofit")

lifestyle_table
```

## Hospital and Community Care Summary Table

```{r hospital_community_care}
indicators <- c(
  "Emergency admissions per 100,000",
  "Unscheduled bed days per 100,000",
  "A&E attendances per 100,000",
  "Delayed discharges (65+) per 100,000",
  "Potentially Preventable Admissions per 100,000"
) |> str_wrap(width = 30)
datatype <- c("rate", "rate", "rate", "rate", "rate")
time <- c(max_fy, max_fy, max_fy, max_fy, max_fy)

# Values
loc_values <- c(latest_emergency_adm_loc$n, latest_bed_days_loc$n, latest_ae_att_loc$n, latest_dd_loc$n, latest_ppa_loc$n[2])
other_loc_values <- bind_rows(other_loc_emergency_adm, other_loc_bed_days, other_loc_ae_att, other_loc_dd, other_loc_ppa)
hscp_values <- c(hscp_emergency_adm$n, hscp_bed_days$n, hscp_ae_att$n, hscp_dd$n, hscp_ppa$n[2])
scot_values <- c(scot_emergency_adm$n, scot_bed_days$n, scot_ae_att$n, scot_dd$n, scot_ppa$n[2])

# Ensure all columns have the same length
n <- length(indicators)
other_loc_values <- other_loc_values[1:n, ]

UC_values <- tibble(
  indicators, datatype, time, loc_values, other_loc_values,
  hscp_values, scot_values
)

colnames(UC_values) <- headings

UC_table <- flextable(UC_values) |>
  bold(part = "header") |>
  bold(j = 1, bold = TRUE, part = "body") |>
  fontsize(part = "header", size = 12) |>
  font(part = "body", fontname = "Arial") |>
  font(part = "header", fontname = "Arial") |>
  color(part = "header", color = "white") |>
  bg(part = "header", bg = "#3F3685") |>
  bg(j = 1:3, part = "body", bg = "grey90") |>
  border(border = fp_border(color = "white", width = 1), part = "body") |>
  set_table_properties(layout = "autofit")

UC_table
```

## Hospital Care (Mental Health) Summary Table

```{r hospital_mental_health}
indicators <- c(
  "Psychiatric patient hospitalisations per 100,000",
  "Unscheduled bed days per 100,000"
) |> str_wrap(width = 30)
datatype <- c("rate", "rate")
time <- c(str_wrap(latest_period_psych_hosp, 9), max_fy)

# Values
loc_values <- c(psych_hosp_latest, latest_bed_days_mh_loc$n)
other_loc_values <- bind_rows(other_locs_psych_hosp, other_loc_bed_days_mh)
hscp_values <- c(hscp_psych_hosp$measure2[2], hscp_bed_days_mh$n)
scot_values <- c(scot_psych_hosp$measure2[2], scot_bed_days_mh$n)


UC_MH_values <- tibble(
  indicators, datatype, time, loc_values, other_loc_values,
  hscp_values, scot_values
)

colnames(UC_MH_values) <- headings

UC_MH_table <- flextable(UC_MH_values) |>
  bold(part = "header") |>
  bold(j = 1, bold = TRUE, part = "body") |>
  fontsize(part = "header", size = 12) |>
  font(part = "body", fontname = "Arial") |>
  font(part = "header", fontname = "Arial") |>
  color(part = "header", color = "white") |>
  bg(part = "header", bg = "#3F3685") |>
  bg(j = 1:3, part = "body", bg = "grey90") |>
  border(border = fp_border(color = "white", width = 1), part = "body") |>
  set_table_properties(layout = "autofit")

UC_MH_table
```
